---
# inventory for lab setup
# https://docs.ansible.com/ansible/latest/collections/cisco/ios/index.html
all:
  vars:
    ansible_httpapi_use_proxy: false
  children:
    ios:
      hosts:
        r1:
          ansible_host: 172.16.0.1
        r2:
          ansible_host: 172.16.0.2
        r3: 
          ansible_host: 172.16.0.3
        r4: 
          ansible_host: 172.16.0.4
        r5: 
          ansible_host: 172.16.0.5
        r6: 
          ansible_host: 172.16.0.6
        r7: 
          ansible_host: 172.16.0.7
        r8: 
          ansible_host: 172.16.0.8
      vars:
        ansible_become: yes
        ansible_become_method: enable
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: admin
        ansible_password: admin