---
- name: Show BGP Neighbors
  hosts: ios

  tasks:
    - name: Show BGP Neighbors
      cisco.ios.ios_command:
        commands: show ip bgp neighbors
      register: result
    - name: Show output
      debug: var=result.stdout_lines
